export const refChartTestData = () => {
 
	// @ts-ignore
	const data = {
		"name":"flare",
		"children":[
			{
				"name":"analytics",
				"children":[
					{
						"name":"cluster",
						"children":[
							{
								"name":"AgglomerativeCluster",
								"value":3938
							},
							{
								"name":"MergeEdge",
								"value":743
							}
						]
					},
					{
						"name":"graph",
						"children":[
							{
								"name":"SpanningTree",
								"value":3416
							}
						]
					},
					{
						"name":"optimization",
						"children":[
							{
								"name":"AspectRatioBanker",
								"value":7074
							}
						]
					}
				]
			},
			{
				"name":"animate",
				"children":[
					{
						"name":"Easing",
						"value":17010
					},
					{
						"name":"FunctionSequence",
						"value":5842
					},
					{
						"name":"interpolate",
						"children":[
				
							{
								"name":"PointInterpolator",
								"value":1675
							},
							{
								"name":"RectangleInterpolator",
								"value":2042
							}
						]
					},
					{
						"name":"Tween",
						"value":6006
					}
				]
			},
			{
				"name":"data",
				"children":[
					{
						"name":"converters",
						"children":[
							{
								"name":"Converters",
								"value":721
							},
						]
					},
					{
						"name":"DataField",
						"value":1759
					},
					{
						"name":"DataSchema",
						"value":2165
					},
					{
						"name":"DataSet",
						"value":586
					},
					{
						"name":"DataSource",
						"value":3331
					},
					{
						"name":"DataTable",
						"value":772
					},
					{
						"name":"DataUtil",
						"value":3322
					}
				]
			},
			{
				"name":"scale",
				"children":[
					{
						"name":"IScaleMap",
						"value":2105
					},
					{
						"name":"LinearScale",
						"value":1316
					},
				]
			},
			{
				"name":"util",
				"children":[
					{
						"name":"Arrays",
						"value":8258
					},
					{
						"name":"Colors",
						"value":10001
					},
				]
			},
			{
				"name":"vis",
				"children":[
					{
						"name":"data",
						"children":[
							{
								"name":"Data",
								"value":20544
							},
							{
								"name":"DataList",
								"value":19788
							},
							{
								"name":"DataSprite",
								"value":10349
							},
							{
								"name":"EdgeSprite",
								"value":3301
							},
							{
								"name":"NodeSprite",
								"value":19382
							},
							{
								"name":"render",
								"children":[
									{
										"name":"ShapeRenderer",
										"value":2247
									}
								]
							},
							{
								"name":"ScaleBinding",
								"value":11275
							},
							{
								"name":"Tree",
								"value":7147
							},
							{
								"name":"TreeBuilder",
								"value":9930
							}
						]
					},
					{
						"name":"legend",
						"children":[
							{
								"name":"Legend",
								"value":20859
							},
							{
								"name":"LegendItem",
								"value":4614
							},
							{
								"name":"LegendRange",
								"value":10530
							}
						]
					},
					{
						"name":"operator",
						"children":[
							{
								"name":"filter",
								"children":[
									{
										"name":"FisheyeTreeFilter",
										"value":5219
									},
									{
										"name":"GraphDistanceFilter",
										"value":3165
									},
									{
										"name":"VisibilityFilter",
										"value":3509
									}
								]
							},
							{
								"name":"IOperator",
								"value":1286
							},
							{
								"name":"label",
								"children":[
									{
										"name":"Labeler",
										"value":9956
									},
									{
										"name":"RadialLabeler",
										"value":3899
									},
									{
										"name":"StackedAreaLabeler",
										"value":3202
									}
								]
							},
							{
								"name":"layout",
								"children":[
									{
										"name":"AxisLayout",
										"value":6725
									},
									{
										"name":"BundledEdgeRouter",
										"value":3727
									},
									{
										"name":"CircleLayout",
										"value":9317
									},
									{
										"name":"CirclePackingLayout",
										"value":12003
									},
									{
										"name":"DendrogramLayout",
										"value":4853
									},
								]
							},
							{
								"name":"Operator",
								"value":2490
							},
							{
								"name":"OperatorList",
								"value":5248
							},
							{
								"name":"OperatorSequence",
								"value":4190
							},
							{
								"name":"OperatorSwitch",
								"value":2581
							},
							{
								"name":"SortOperator",
								"value":2023
							}
						]
					},
					{
						"name":"Visualization",
						"value":16540
					}
				]
			}
		]
	}

  return data
}